type Flow {
  flow_name: String
  flow_description: String
  flow_synonyms: String
  #infrastructure_flow: Boolean
  flow_formula: String
  flow_cas: String
  flow_type: String
  database:String
  #flow_category_id:String
  #flow_category_name:String
  flow_properties:String
  flow_categories:Category
  flow_locations:Location
}

type Process{
  process_name:String
  process_description:String
  process_type:String
  process_allocation_method_default:String
  process_allocation_factors:String
  process_exchanged_flows:String
  process_parameters:String
  process_locations:Location
  database:String
  process_valid_period:Time
  process_categories:Category
  documentations:Ducumentation
  data_descriptions:DataDescription
  data_quality_systems:DataQualitySystem
}
type DataDescription{
  collection:String
  selection:String
  treatment:String
  sampling:String
  completeness:String
}

type FlowProperty{
  flow_property_name:String
  flow_property_description:String
  flow_property_type:String
  flow_property_categories:Category
}

type Time{
  time_from:[String]
  time_until:[String]
}

type Category{
  #category_id:String
  category_name:String
  category_subclass:String
  category_class:[String]
}

type Location{
  name:String
  code:String
  description:String
  longitude:Float
  latitude:Float
  geometry_type:String
  geometry_geometries:String
}

type Ducumentation{
  time:String
  technology:String
  geography:String
  project:String
  inventory_method:String

  modeling_constants:String
  intended_applications:String
  restrictions:String

  copyright:Boolean
  creation_date:String
  
  review_details:String
  sources:String

  publication:Source
  documentor:Actor
  generator:Actor
  reviewer:Actor
  owner:Actor
}


type Source{
  name:String
  description:String
  year:String
  text_reference:String
  url:String
  categories:Category
}

type DataQualitySystem{
  data_quality_system_name:String
  data_quality_system_description:String
  data_quality_system_has_uncertainty:Boolean
  data_quality_system_indicators:String
  data_quality_system_source:Source
}

type Actor{
  name:String
  description:String
  telefax:String
  website:String
  address:String
  email:String
  telephone:String
  country:String
  city:String
  zip_code:String
  categories:Category
}


type LCIA_Methods{
  LCIA_method_name:String
  LCIA_method_description:String
  LCIA_method_impact_categories:String
  LCIA_method_nw_sets:String
}

type LCIA_Categories{
  LCIA_category_name:String
  LCIA_category_description:String
  LCIA_category_reference_unit_name:String
  LCIA_category_impact_factors:String
}

type LCIA_NW_Sets{
  LCIA_NW_Set_name:String
  LCIA_NW_Set_description:String
  LCIA_NW_Set_factor:String
  LCIA_NW_Set_weighted_score_unit:String
}

type Query {
  Flows: [Flow]
  Processes: [Process]
  Categories:[Category]
  FlowProperties:[FlowProperty]
}
